version: "3.9"

services:
  backend:
    build: .
    container_name: coffee_shop_backend
    environment: 
      - .env # Sử dụng file .env từ thư mục gốc
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: coffee_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: